apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
commonLabels:
  environment: prod
patchesStrategicMerge:
- patch.yaml
images:
- name: akiragenocyber/example-app
  newTag: 1.1.1
